# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 690d304176c088b90442d216b6e281672c6c4aee312d101bcc8cd64b7e70c084a138d8c71bf1ffaede513807372562b01169b9a48ac71d54295d683118f5d9d9

test:
  secret_key_base: 493ccda5ebebfdccc709af6842c90988373472bf954a3d5ed1d8ad577e6c683ea7d4cae79dc85908da99da7dc1cd6f63e392fd2b2bc65543cd5617819751878c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
